
public enum ETestType {
	SINGLE_INSTANCE, 
	MULTIPLE_INSTANCE, 
	PARAMETER_TUNNING_FOR_LIST_LENGTH,
	PARAMETER_TUNNING_FOR_POSITION,
	COMPARE_SELECTION_TYPE,
	COMPARE_KNOWLEDGE_TYPE,
	PARAMETER_TUNING
}
